### PR TITLE
Plm pep8

### PR DESCRIPTION
**Pull request by SalahAdDin**
I want to work in fix all `pep8` problems with this module, but it will take much time.

### CODE REVIEW

**Review by OmniaGit — COMMENTED** [review]
We prefer to have single import for each module
this is more clean and in case of import error it gives exactly the module that brakes

**Comment by SalahAdDin** [comment]
@OmniaGit I got it, i will change it.

**Review by OmniaGit — CHANGES_REQUESTED** [review]
Do not change the function name, because they are used from the client side, from xml-rpc call.
You will brake the client in this way

**Comment by SalahAdDin** [comment]
@OmniaGit But, i also change the function names in the `xml` files(reports and views).

**Pull request merged**
