### PR TITLE
[11.0][plm] Improving  views.

### PR DESCRIPTION
**Pull request by SalahAdDin**
I'm adding some features that can improve the user experience in this module:
- Images in `plm.component` view and in `kanban`view.
- Component name section as a normal product name section.
- The user can choose the component category.
- The user can choose if the component can be sold or purchased.
- Removed useless page `TitleBlocks`.

### CODE REVIEW

**Comment by OmniaGit** [comment]
the title-block page is very useful for the engineering dep. because the value listed there are the value used in cad drawings, it's useful for checking. may be it's better to show it only for plm users

**Comment by SalahAdDin** [comment]
@OmniaGit, In that case, it needs a better name: TItle-block does not say anything to the user.

**Comment by OmniaGit** [comment]
the cad users know it very well .. but we can change it in CAD Property if it sound better

**Comment by SalahAdDin** [comment]
`CAD Property` ?

Ok, it sounds better.

**Review by OmniaGit — APPROVED** [review]

**Pull request merged**
