### PR TITLE
fix NewRevision for plm_web_revision module

### PR DESCRIPTION
**Pull request by duplomatic-anava**
Just missing an argument :)

### CODE REVIEW

**Review by OmniaGit — CHANGES_REQUESTED** [review]
the newRevision dose not accept arguments for products

your fix it's ok for the ir_attachemnt but not for the product.

please could you  fix it ?

thanks
Regards
Matteo

**Comment by duplomatic-anava** [comment]
Thank your for the reply Matteo.

line 54 of product_product_extended.py -> to be restored with the docId
line 1351 product_product.py -> possibly we should also add docBrws.NewRevision(docBrws.id) -> please confirm

In addition:
`
    @api.multi
    def newVersion(self):
        """
            create a new version of the document (to WorkFlow calling)
        """
        if self.NewRevision() is not None:
            return True
        return False
`

newVersion is not called anywhere in ir_attachments.py, but docId should be supplied. How can we handle this line?

Thank you.

Alessio

**Comment by OmniaGit** [comment]
Dear Alessio,
`plm_web_revision/models/product_product_extended.py`
must be keep d  as it was "No Arguments"
`revRes = prodBrws.NewRevision()`

the modification on the ir_attachment is right.

our module have a lot of function that is used on the cad connector(Client) so the revision one is one of this.
regards,
Matteo

**Comment by duplomatic-anava** [comment]
Dear Matteo,

now I understand the comment:

> create a new version of the document (to WorkFlow calling)

As per the correction, I think it should be looking at the ir_attachment class member self.id but I am not sure. Please check the commit.

Thank you.

Alessio

**Review by OmniaGit — APPROVED** [review]
perfect.

**Pull request merged**
